
export const Images = {
    WelcomeImage:require('./WelcomeBackground.png'),
    Info1:require('./Info1.png'),
    Info2:require('./Info2.png'),
    Info3:require('./Info3.png'),
    UploadVedio:require('./UploadVedio.png'),
    Elipse:require('./Elipse.png'),
    VedioIcon:require('./VedioIcon.png'),
    GeneratingVedio:require('./GeneratingVedio.png'),
    VedioPreviewIcon:require('./VedioPreviewIcon.png'),
    DefaultProfile:require('./DefaultProfile.png'),
    ProPlanIcon:require('./ProPlanIcon.png'),
    VedioIcon2:require('./VedioIcon2.png'),
    CharacterIcon:require('./CharacterIcon.png'),
    TempCharacher:require('./TempCharacher.png'),
    ProjectIcon:require('./ProjectIcon.png'),
    TempAnchorImage:require('./TempAnchorImage.png'),
    FreePlanIcon:require('./FreePlanIcon.png'),
    ProPlanIcon2:require('./ProPlanIcon2.png'),
    EnterPriseIcon:require('./EnterPriseIcon.png'),
    TickIcon:require('./TickImage.png'),
    CrossImage:require('./CrossImage.png'),
    ProcessingImage:require('./ProcessingImage.png'),
    LanguageImage:require('./LanguageImage.png'),
    SplashScreenIcon:require('./SplashScreenIcon.png'),
    // Character images
    CharacterBody:require('./charcheter/Body.png'),
    CharacterBeard:require('./charcheter/beard.png'),
    CharacterLips:require('./charcheter/lips.png'),
    CharacterEye:require('./charcheter/eye.png'),
    CharacterCap:require('./charcheter/cap.png'),
    CharacterGlasses:require('./charcheter/Glasses.png'),
};